name: Docker Image CI

on:
  workflow_dispatch:
  schedule:
    - cron: 59 23 * * *

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build vmbot Image
      run: docker build . --file ./vmbot-arm64/Dockerfile --tag kry9ton/vmbot:arm64 && docker push kry9ton/vmbot:arm64
