name: Docker Image CI

on:
  workflow_dispatch:
  schedule:
    - cron: 59 23 * * *

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@master
      with:
        platforms: all
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master
    - name: Build
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: .
        file: ./vmbot-arm64/Dockerfile
        platforms: linux/arm64
        push: false
        tags: ${{ steps.prep.outputs.tags }}
